const URL_SERVER = 'http://18.218.201.243:8080'
const USERS = '/users'
const TRANSACTIONS = '/transactions'
const LOGIN = '/login'
const CATEGORIES = '/categories'
const ACCOUNTS = '/accounts'
const ACCOUNTS_SEARCH_BY = '/accounts/search/by'
